In [1]:
import pandas as pd

In [2]:
white_wines = pd.read_csv("white_wine.csv", sep=";", skipinitialspace=True, header=0)

In [3]:
white_wines

,fixedacidity,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,pH,sulphates,alcohol,quality
0,7,",27",",36","20,7",",045",45,170,"1,001",3,",45","8,8",4
1,"6,3",",3",",34","1,6",",049",14,132,",994","3,3",",49","9,5",4
2,"8,1",",28",",4","6,9",",05",30,97,",9951","3,26",",44","10,1",4
3,"8,1",",28",",4","6,9",",05",30,97,",9951","3,26",",44","10,1",4
4,"6,2",",32",",16",7,",045",30,136,",9949","3,18",",47","9,6",4
...,...,...,...,...,...,...,...,...,...,...,...,...
3929,"4,9",",235",",27","11,75",",03",34,118,",9954","3,07",",5","9,4",4
3930,"6,2",",21",",29","1,6",",039",24,92,",99114","3,27",",5","11,2",4
3931,"6,6",",32",",36",8,",047",57,168,",9949","3,15",",46","9,6",3
3932,"6,5",",24",",19","1,2",",041",30,111,",99254","2,99",",46","9,4",4
3933,"5,5",",29",",3","1,1",",022",20,110,",98869","3,34",",38","12,8",5

Widać, że mamy tutaj przecinki które psują nam liczby. Wczytajmy jeszcze raz plik zamieniając separator dziesiętny na przecinek.

In [4]:
white_wines = pd.read_csv("white_wine.csv", sep=";", decimal=',', skipinitialspace=True, header=0)

In [5]:
white_wines

,fixedacidity,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,4
1,6.3,0.300,0.34,1.60,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,4
2,8.1,0.280,0.40,6.90,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,4
3,8.1,0.280,0.40,6.90,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,4
4,6.2,0.320,0.16,7.00,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,4
...,...,...,...,...,...,...,...,...,...,...,...,...
3929,4.9,0.235,0.27,11.75,0.030,34.0,118.0,0.99540,3.07,0.50,9.4,4
3930,6.2,0.210,0.29,1.60,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,4
3931,6.6,0.320,0.36,8.00,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,3
3932,6.5,0.240,0.19,1.20,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,4
3933,5.5,0.290,0.30,1.10,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,5

Sprawdźmy typy danych dla zmiennych. Zakładam też na potrzeby projektu aby oddać jak najlepiej ralia wina, że zmienne są przedstawione w następujących jednostkach:\
Stała dysocjacji (kwasowość) - bezwymiarowa,\
Kwasowość lotna - [g/l],\
Kwasek cytrynowy - [g/l],\
Cukier resztkowy - [g/l],\
Chlorki - [g/l],\
Wolny dwutlenek siarki - [mg/l],\
Całkowity dwutlenek siarki - [mg/l],\
Gęstość - [kg/m^3],\
pH - samo w sobie jest jednotką,\
Siarczany - [%],\
Alkochol - [%],\
Jakość - bezwymiarowa

In [6]:
white_wines.columns = ['Fixed acidity', "Volatile acidity", "Citric acid", "Residual sugar", "Chlorides", "Free sulfur dioxide", "Total sulfur dioxide", "Density", "pH", "Sulphates", "Alcohol", "Quality"]

In [7]:
white_wines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3934 entries, 0 to 3933
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Fixed acidity         3934 non-null   float64
 1   Volatile acidity      3934 non-null   float64
 2   Citric acid           3934 non-null   float64
 3   Residual sugar        3934 non-null   float64
 4   Chlorides             3934 non-null   float64
 5   Free sulfur dioxide   3934 non-null   float64
 6   Total sulfur dioxide  3934 non-null   float64
 7   Density               3934 non-null   float64
 8   pH                    3934 non-null   float64
 9   Sulphates             3934 non-null   float64
 10  Alcohol               3934 non-null   float64
 11  Quality               3934 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 368.9 KB

In [8]:
for variable in white_wines.columns:
    print(variable, " : ", white_wines[variable].unique(), "\n")

Fixed acidity  :  [ 7.    6.3   8.1   6.2   8.6   7.9   6.6   7.4   6.4   8.5   8.3   5.8
  7.3   6.5   6.7   7.2   6.8   6.9   6.    7.1   6.1   7.5   9.8   5.5
  5.9   7.8   8.2   7.6   5.2  10.2   5.6   5.7   7.7   5.3   5.4   9.1
  5.    8.   10.    5.1   9.2   8.4   8.8   8.7   9.4   9.6   9.7  10.3
  9.   10.7   8.9   9.3   9.9   9.5  11.8   4.6   6.15  4.5   7.15  6.45
  4.2   4.9   4.8   4.7   3.8   4.4   3.9 ]

Volatile acidity  :  [0.27  0.3   0.28  0.32  0.22  0.23  0.18  0.16  0.17  0.48  0.66  0.34
 0.31  0.25  0.24  0.14  0.12  0.39  0.33  0.45  0.46  0.19  0.2   0.38
 0.47  0.35  0.26  0.54  0.43  0.44  0.21  0.265 0.36  0.305 0.13  0.41
 0.485 0.425 0.37  0.255 0.595 0.29  0.42  0.245 0.685 0.495 0.64  0.4
 0.115 0.58  0.585 0.59  0.6   0.15  0.55  0.1   0.335 0.905 0.49  0.155
 0.52  0.51  0.62  0.345 0.475 0.56  0.105 0.57  0.67  0.5   0.11  0.225
 0.395 0.655 0.205 0.415 0.705 0.08  0.68  0.275 0.61  0.365 0.165 0.145
 0.85  0.185 0.325 0.445 0.545 0.91  0.53  0.71  1.005 0.76  0.93  0.295
 0.695 0.285 0.175 0.615 0.315 0.235 0.965 0.375 0.125 0.74  0.215 0.435
 0.75  0.085 0.73  0.455 1.1   0.65  0.555 0.63  0.69  0.785 0.385 0.405]

Citric acid  :  [0.36 0.34 0.4  0.16 0.43 0.41 0.37 0.38 0.04 0.48 0.42 0.32 0.39 0.2
 0.23 0.26 0.25 0.31 0.29 0.33 0.35 0.59 0.15 0.24 0.07 0.03 0.13 0.28
 0.46 0.3  0.61 0.62 0.63 0.66 0.5  0.   0.56 0.27 0.67 0.14 0.45 0.47
 0.44 0.88 0.21 0.22 0.08 0.54 0.49 0.58 0.7  0.6  0.51 0.1  0.19 0.09
 0.12 0.02 0.65 0.17 0.71 0.06 0.68 0.72 0.18 0.57 0.05 0.52 1.   0.01
 0.74 0.81 0.55 0.69 0.64 0.73 0.53 0.99 0.78 0.79 0.8  0.11 0.91]

Residual sugar  :  [20.7   1.6   6.9   7.    1.5   1.45  4.2   1.2   1.1   2.9   1.3   9.
  8.7  10.4   2.05 14.95  1.7   5.4  17.95  7.4   4.4   1.    0.9  12.4
  4.6   4.9   6.4   2.1  10.1   7.8   4.8   1.4   8.2  11.8  11.   13.3
  7.5   1.8  15.9  10.5  13.5   9.6  12.1  18.9  14.4  16.5   9.2   3.3
  5.7  12.2   6.85  5.    7.6   2.8   2.7  13.1  15.8  15.7   1.9   2.2
  4.3   2.    5.2   4.1  10.2  14.   14.5   8.95  9.85  0.8   4.55 17.7
  5.1  12.9   5.5  22.   11.9   9.4   8.5   8.    3.6   3.5  16.1  13.2
 13.9   2.3  11.6   8.3   6.2   9.7   5.3  17.5   9.5  17.8   2.4  14.3
 15.55 11.2  16.2  13.6  19.45  7.1  10.7   9.1   4.7  15.6  15.4   7.2
 14.2   5.8  19.8   7.3  10.6   3.8   6.8   6.7   3.7   6.6   7.7   7.85
  9.3   9.9  12.3   3.    2.5  12.5   3.2   5.9  14.9   9.8  18.2   6.3
  4.   18.95 12.7   8.6  20.8   2.6  15.2  10.   12.15  3.4   4.5   8.9
 10.8  16.7   2.25 12.6  15.3   8.8  10.3  16.3   6.    7.9  11.4  17.75
 10.9  18.05 11.5  12.    4.75 11.3  13.   14.8  18.75 13.8   8.1   7.35
 11.1  19.3  18.6  13.4  15.   14.1  13.7  17.45  6.35 16.95 17.1   8.4
  1.95 14.35 12.85 16.85 14.45 14.75  6.5   1.15 17.55  5.15 14.6  17.35
  3.75  3.9  14.15  3.1  17.85  4.45  1.35  8.65 12.8  18.15 23.5  11.7
 16.8   3.95 31.6  18.35  1.55  6.1  19.5   1.05 19.6   9.25  9.05 15.1
  5.6  16.05 18.3  17.2  16.6   5.25 17.3   0.6   8.45 16.9  16.75 15.75
 12.05 11.95 16.45 19.35 11.75  7.05 16.    4.85 19.95 18.1   0.7  20.4
  0.95  5.95  9.65 16.4  10.05  1.65 65.8  20.2   1.25  8.75  5.45 14.05
 10.55  8.25 14.7  17.6   6.75 12.75  2.65  8.55  4.35  2.35 13.65  6.65
 13.55 11.25  5.55  9.55 14.55 15.25  3.15 18.5   5.35  3.85  8.15 15.5
 19.9  16.65  7.25  6.55 26.05 18.8  17.4  16.55  7.95 17.9  18.    7.75
 13.15 20.3  11.45 17.05  9.15 22.6   1.75  4.25 19.25  1.85 12.55 18.4
 19.4 ]

Chlorides  :  [0.045 0.049 0.05  0.044 0.033 0.035 0.04  0.032 0.046 0.029 0.038 0.052
 0.051 0.047 0.042 0.08  0.053 0.057 0.173 0.069 0.063 0.066 0.062 0.068
 0.147 0.039 0.048 0.092 0.064 0.041 0.056 0.061 0.054 0.043 0.06  0.034
 0.059 0.065 0.058 0.026 0.036 0.027 0.037 0.055 0.2   0.197 0.03  0.07
 0.031 0.074 0.132 0.071 0.089 0.021 0.108 0.028 0.022 0.081 0.023 0.073
 0.346 0.025 0.09  0.114 0.186 0.067 0.18  0.083 0.096 0.094 0.29  0.02
 0.185 0.024 0.11  0.078 0.13  0.135 0.115 0.072 0.018 0.119 0.126 0.017
 0.15  0.152 0.088 0.244 0.137 0.093 0.077 0.079 0.076 0.201 0.301 0.138
 0.168 0.122 0.167 0.239 0.123 0.133 0.211 0.255 0.204 0.208 0.086 0.084
 0.16  0.087 0.217 0.157 0.148 0.085 0.091 0.095 0.142 0.075 0.014 0.156
 0.019 0.012 0.17  0.171 0.082 0.016 0.112 0.154 0.104 0.102 0.184 0.146
 0.117 0.118 0.009 0.098 0.194 0.144 0.097 0.209 0.105 0.176 0.015 0.271
 0.12  0.175 0.174 0.127 0.136]

Free sulfur dioxide  :  [ 45.   14.   30.   28.   11.   17.   16.   48.   29.   19.   56.   32.
  20.    7.   31.   43.   22.   21.   25.   38.   63.   62.   39.   50.
  44.   27.   81.   50.5   9.   34.   42.   54.   52.   55.   69.   65.
  47.   51.   26.   15.    4.   64.   60.   37.   68.    8.   57.   46.
  59.   36.   49.   18.   24.   23.   58.   41.   12.    5.   33.   61.
  66.   75.   76.   53.   35.   40.   64.5   3.   82.  131.   38.5  82.5
  13.   73.5  67.   79.   70.   10.    6.   77.  122.5  78.   83.   44.5
  35.5  73.   71.   88.   77.5  41.5 118.5  96.   52.5 146.5  72.   48.5
 128.  110.   42.5  39.5  19.5  85.   74.   89.   86.   93.  138.5  95.
 124.  105.  101.  108.   79.5  61.5  98.  112.   70.5  23.5  59.5  28.5
  60.5  43.5 289.   97. ]

Total sulfur dioxide  :  [170.  132.   97.  136.  129.   63.  109.   75.  143.  112.   99.  171.
 102.  142.  245.  141.   47.  100.  117.  179.  123.  149.  138.  157.
 160.  206.  207.  173.  124.   82.  108.  191.  147.   78.  111.  151.
 120.  174.   96.  105.  244.  238.5 201.   72.   87.  114.  155.  152.
 156.  202.  243.  148.  240.  164.   80.   83.  192.  162.  187.  195.
 150.  103.   85.  196.  131.  146.  126.  203.  184.  241.  188.  121.
  79.   77.  107.  116.  135.   76.  198.  119.  159.  110.  133.  130.
  65.  176.  183.  167.  227.  226.  230.  166.  210.  211.  181.  180.
 214.  204.  236.  134.  153.   68.  122.  161.  172.  144.  140.  145.
 200.  194.   90.  218.5 249.5 199.  197.  118.   95.  231.  234.   67.
 190.  182.  169.   74.  163.  127.  137.  313.   91.  139.  128.  178.
  89.   98.  125.  115.  260.   66.   69.   93.  252.  221.  222.   84.
 104.  186.  113.  158.   86.  165.  177.  189.   55.  154.   41.  101.
  29.   61.  168.   37.  185.   81.  106.   94.  228.  234.5 224.  193.
 225.  213.   49.   57.  253.  175.  247.  238.   46.   92.  215.  220.
 205.  229.  212.   73.   64.  242.   30.  233.   88.   54.  217.  216.
  60.  232.  223.  219.  189.5 129.5  59.  251.  366.5  48.   51.  209.
  24.   56.   53.  235.  208.  249.  248.   71.  307.5 256.  212.5 344.
 282.  218.  219.5 216.5  28.  303.   45.   70.  272.   58.   18.   34.
  50.  237.    9.   40.  176.5 115.5 259.  162.5 440.   44. ]

Density  :  [1.001    0.994    0.9951   0.9949   0.9938   0.9908   0.9947   0.992
 0.9912   0.9914   0.9928   0.9892   0.9917   0.9955   0.9961   0.9974
 0.9934   0.9939   0.9962   0.9905   0.9906   0.9999   0.9937   0.9954
 0.991    0.9911   0.993    0.9972   0.9931   0.9926   0.9903   0.9956
 0.9958   0.9964   0.9941   0.9898   0.9929   0.9966   0.9975   0.9957
 0.99     0.9899   0.9916   0.9969   0.9979   0.9913   0.997    1.
 0.999    0.9927   0.9982   0.9968   0.9984   0.9952   0.9924   0.9923
 0.9921   0.9919   0.9894   0.998    0.9932   0.9902   0.9918   0.995
 0.9936   0.9942   0.9973   0.9944   0.9989   0.9971   0.9998   0.9976
 0.996    0.9935   0.9904   0.9977   0.9996   0.9965   0.9945   0.9909
 0.9988   0.9978   0.9933   0.9946   0.9948   0.9995   0.9893   0.9983
 0.9896   0.9959   0.9922   0.9907   0.9915   0.9901   0.9987   0.9967
 0.9963   0.9993   0.9986   0.9925   0.9981   0.9997   0.9943   0.99855
 0.99345  0.99475  0.99325  1.0002   0.99685  0.99455  0.99035  0.99225
 0.99695  0.99115  0.99535  0.9953   0.99755  1.00055  0.9985   0.99175
 0.99985  0.99215  0.9992   1.0006   0.99135  0.99715  0.99865  0.99815
 0.99335  0.99625  0.99445  0.99085  0.99775  0.99795  0.99745  0.99405
 0.99785  0.99675  0.98965  0.99055  0.99155  0.99975  0.99845  0.99315
 0.99725  0.99255  0.9886   0.9994   0.99185  0.99425  0.99495  0.99505
 0.99265  0.99965  1.0004   0.989    1.0003   1.0001   1.0005   1.0012
 0.98815  1.0024   1.0103   1.0008   0.99705  0.99605  1.0007   0.9991
 1.0017   1.0011   0.9897   0.99416  0.99516  0.99496  0.99579  0.99471
 0.99699  0.99758  0.99243  1.00182  0.99212  0.99449  0.99748  0.99189
 0.99827  0.99752  0.99479  1.00047  0.99382  0.99784  0.99537  0.99838
 0.99566  0.99268  0.99468  0.99307  0.99907  0.99148  0.99383  0.99508
 0.99235  0.99084  0.99856  0.99591  0.99173  0.99378  0.99805  0.99534
 0.99061  0.99182  0.99814  0.99379  0.99426  0.99228  0.99595  0.99297
 0.99687  0.99154  0.98993  1.00241  0.99437  0.99756  0.99572  0.99254
 0.99509  0.99676  0.99194  0.99077  0.99782  0.99942  0.99353  0.99256
 0.99199  0.99354  0.99244  0.99831  0.99524  0.99802  0.99512  0.99438
 0.99679  0.99652  0.99698  0.99474  0.99511  0.99125  0.99556  1.00098
 0.99518  0.99347  0.99362  0.99361  0.99114  0.99453  0.99806  1.00016
 0.99116  0.99319  0.99517  0.99514  0.99166  0.99558  0.99399  0.99741
 0.99622  0.99803  0.99773  0.99274  1.00118  0.99176  0.99411  0.99577
 0.99564  0.99578  0.99888  1.00014  0.99594  0.99434  0.99203  0.99316
 0.99612  0.99295  0.99394  0.99642  0.99248  0.99954  0.99592  0.99692
 0.99822  0.99402  0.99404  0.99787  0.99839  0.99571  0.99658  0.99076
 0.99542  0.99825  0.99289  0.99432  0.99662  0.99088  0.99922  0.99466
 0.99836  0.99238  0.99645  0.99543  0.99526  0.99732  0.99573  0.99656
 0.99112  0.99214  0.99004  0.99463  0.99683  0.99596  0.99898  0.99342
 0.99772  0.99502  0.99207  0.99497  0.99828  0.99669  0.99544  0.99944
 0.99066  0.99106  0.99696  0.99167  0.99902  0.98992  0.99582  0.99352
 0.99273  0.99628  0.99553  0.98914  0.99976  0.99808  0.99499  0.99655
 0.99296  0.99482  0.99079  0.98958  0.99938  0.99059  0.99835  0.99159
 0.99563  0.98931  0.99691  0.99678  0.99089  0.99332  0.99272  0.99636
 0.99202  0.99064  0.99884  1.00013  0.99132  0.99488  0.99527  0.99198
 0.98936  0.99786  0.98974  0.99044  0.98892  0.99334  0.99094  0.99014
 0.99304  0.98944  0.99367  0.99183  0.99428  0.99388  0.99208  0.99216
 0.99165  0.99924  0.99562  0.99541  0.99168  0.99873  0.99172  0.99278
 0.99053  0.99858  0.99092  0.99727  0.99026  0.99144  0.99015  0.99693
 0.99006  0.98994  0.98985  0.99882  0.99477  0.99478  0.99955  0.99374
 0.99237  0.99022  0.99032  1.03898  0.99587  0.99552  0.98894  0.99068
 0.98964  0.99584  0.99067  0.98912  0.99052  0.99644  0.99095  0.99188
 0.99581  0.99142  0.99232  0.99311  0.99093  0.99156  0.98984  0.99008
 0.9889   0.99178  0.99046  0.98999  0.98946  0.98976  0.99672  0.98945
 0.98883  0.99075  0.99436  0.99195  0.99313  0.9895   0.99848  0.99413
 0.98982  0.98934  0.99629  0.99326  0.99834  0.99555  0.99218  0.99397
 0.99601  0.98713  0.99308  0.99494  0.98986  0.98951  0.99634  0.99368
 0.99792  0.98919  0.99104  0.99038  0.99286  0.99604  0.99007  0.99507
 0.99011  0.99184  0.99469  0.99406  0.99305  0.99096  0.98956  0.9888
 0.98942  0.99082  0.98802  0.99074  0.99941  0.99206  0.99016  0.99439
 0.99458  0.99418  0.99456  0.99546  0.99646  0.99264  0.99489  0.99519
 0.99666  0.99324  0.99086  0.99711  0.99452  0.99427  0.99152  0.98876
 0.99174  0.99454  0.99778  0.99205  0.98962  0.99118  0.99164  0.98972
 0.99253  0.98906  0.99146  0.99121  0.98924  0.99366  0.99126  0.99129
 0.99513  0.98836  0.99586  0.99322  0.99098  0.99918  0.99293  0.99851
 0.99946  0.99568  0.98865  0.99684  0.99036  0.99222  0.98961  0.99422
 0.98926  0.98988  0.98939  0.99318  0.99196  0.99306  0.99111  0.99124
 0.99234  0.99033  0.99057  0.99127  0.98938  0.99001  0.99386  0.98916
 0.99276  0.99158  0.99548  0.99412  0.99123  0.99328  0.99031  0.99119
 0.99245  0.99162  0.99632  0.99177  0.98923  0.99358  0.99688  0.99407
 0.99226  0.99193  0.99091  0.99134  0.99229  0.99396  0.99338  0.99056
 0.99128  0.98896  0.99012  0.98902  0.99395  0.99539  0.98889  0.99833
 0.98853  0.99266  0.99204  0.99472  0.99384  0.98862  0.99151  0.99072
 0.98954  0.98794  0.99355  0.99336  0.98882  0.99042  0.99139  0.99576
 0.99657  0.99392  0.99242  0.99947  0.99945  0.99375  0.99153  0.98834
 0.99138  0.98928  0.99246  0.99956  0.99058  0.99192  0.99536  0.99616
 0.98918  0.99532  0.99284  0.99393  0.99408  0.99473  0.98998  0.99742
 0.98922  0.99869  0.99108  0.99606  0.98987  0.98947  0.98819  0.99133
 0.99143  0.99312  0.99528  0.99279  0.99704  0.99224  0.98959  1.00037
 0.99062  0.99398  0.99211  0.99492  0.99043  0.99654  0.99794  0.99726
 1.00295  0.99054  0.99048  0.99459  0.99966  0.99283  0.99916  0.99498
 0.98856  0.99346  0.99523  0.98742  0.99275  1.00044  0.99444  0.99344
 0.98949  0.98722  0.99754  0.99712  0.99373  0.99904  0.99299  1.00022
 0.99936  0.98953  0.99186  0.99567  0.9874   0.99122  0.99099  0.99776
 0.99551  0.99702  0.99109  0.99677  0.99522  0.99429  0.99002  0.99294
 0.99262  0.98913  0.99021  0.99728  0.99364  0.99018  0.98968  0.99864
 0.99545  0.99665  0.99069  0.99896  0.98746  0.99028  0.99751  0.98867
 0.99249  0.99239  0.99872  0.988245 0.99486  0.99282  0.99281  0.99047
 0.99223  0.99863  0.99317  1.00038  0.99424  0.99626  0.99287  0.99971
 0.99314  0.99565  0.99027  0.99302  0.99257  0.99506  0.99706  0.99588
 0.99608  0.99024  0.98978  0.99908  0.99853  0.99734  0.99737  0.99767
 0.98711  0.99481  0.99019  0.99659  0.99107  0.99708  0.99163  0.99065
 0.98948  0.99045  0.99348  0.99013  0.99624  0.99602  0.99718  0.99464
 0.99261  0.99736  0.99041  0.99105  0.99209  0.99251  0.9887   0.98952
 0.99267  0.99269  0.99862  0.98886  0.99288  0.99462  0.99476  0.99081
 0.98997  0.99681  0.99538  0.99627  0.99433  0.99807  0.99738  0.98963
 0.99136  0.99323  0.99504  0.99561  0.99663  0.99157  0.99899  0.99804
 0.99724  0.99461  0.99391  0.99824  0.99906  0.99415  0.99611  0.99179
 0.99339  0.99241  0.98816  0.99911  0.99356  0.98898  0.989435 0.998275
 0.98823  0.998365 0.99837  0.98895  0.99331  0.99435  0.99414  0.99201
 0.98774  0.98966  0.99309  0.98868  0.98975  0.99365  0.99161  0.99271
 0.98845  0.99097  0.99521  0.99321  0.99943  0.9891   0.98872  0.99171
 0.98904  0.98758  0.98981  0.99051  0.99252  0.99103  0.99258  0.99005
 0.98854  0.98869 ]

pH  :  [3.   3.3  3.26 3.18 3.22 2.99 3.14 3.54 3.25 3.24 3.33 3.12 3.17 3.42
 3.38 3.19 3.2  3.47 3.37 3.13 3.21 3.1  3.27 3.35 3.34 3.32 3.31 3.05
 3.11 3.36 3.03 3.02 3.69 2.95 3.39 3.09 3.04 2.89 3.4  3.16 3.01 3.63
 3.29 3.45 3.23 3.15 3.06 2.98 3.28 3.08 2.87 2.93 3.44 3.5  3.48 3.72
 3.53 3.52 2.96 3.61 3.49 3.51 3.46 3.07 2.97 3.43 3.64 3.56 2.86 2.94
 2.88 2.85 3.41 3.58 3.55 3.66 3.59 2.74 2.92 3.82 3.81 3.65 2.9  3.62
 2.91 3.74 3.6  2.72 2.79 3.57 3.8  3.68 2.77 3.79 3.7  2.8  2.84 3.77
 2.83 3.75 2.82 3.76 3.67]

Sulphates  :  [0.45 0.49 0.44 0.47 0.56 0.53 0.63 0.52 0.55 0.36 0.39 0.35 0.5  0.4
 0.51 0.37 0.42 0.28 0.34 0.46 0.58 0.38 0.54 0.64 0.6  0.71 0.77 0.48
 0.41 0.3  0.59 0.57 0.43 0.84 0.33 0.29 0.27 0.68 0.66 0.61 0.32 0.79
 0.7  0.65 0.67 0.62 0.76 0.74 0.69 0.72 0.73 0.78 0.96 0.97 0.82 0.75
 0.95 0.31 0.88 0.25 0.8  0.87 0.86 0.9  0.81 0.92 0.26 0.98 1.06 0.89
 0.94 0.99 0.22 0.23 0.85 0.83 1.08]

Alcohol  :  [ 8.8         9.5        10.1         9.6        11.         12.
  9.7        10.8        12.4        11.4        12.8        11.3
 10.         10.4        10.5        11.6        10.2         9.
 11.2         8.6         9.4         9.8        11.7        10.9
  9.1         8.9         9.9        12.6        10.7        12.7
 10.6         8.7        11.5         9.2        10.3        11.8
 12.1         9.3        11.1        12.3         8.5        12.5
 11.9        12.2        12.9        13.9        14.         13.5
 13.3        13.2        13.4        13.7        13.          8.
 13.1        13.6         8.4        11.94       12.89333333 11.46666667
 10.98       11.43333333 10.53333333  9.53333333 10.93333333 11.36666667
 11.33333333 11.06666667  9.73333333 11.35        9.55       10.55
 11.45       14.05       12.33333333 11.05       12.75       13.8
 13.05       11.26666667 10.56666667 11.73333333 11.75       10.65
 10.96666667 10.13333333 10.15       10.46666667 11.63333333 12.25
 11.85       11.65       13.55       13.13333333 11.95       12.06666667
 11.55        9.63333333 12.15      ]

Quality  :  [4 3 5 6 2 1 7]

In [9]:
white_wines.describe()

,Fixed acidity,Volatile acidity,Citric acid,Residual sugar,Chlorides,Free sulfur dioxide,Total sulfur dioxide,Density,pH,Sulphates,Alcohol,Quality
count,3934.000000,3934.000000,3934.000000,3934.000000,3934.000000,3934.000000,3934.000000,3934.000000,3934.000000,3934.000000,3934.000000,3934.000000
mean,6.849797,0.279146,0.333622,6.459558,0.045601,35.439883,138.869853,0.994068,3.189156,0.489858,10.501906,3.862989
std,0.838729,0.102392,0.120268,5.134349,0.021445,17.244178,42.456374,0.003028,0.152655,0.114667,1.226966,0.887400
min,3.800000,0.080000,0.000000,0.600000,0.009000,3.000000,9.000000,0.987110,2.720000,0.220000,8.000000,1.000000
25%,6.300000,0.210000,0.260000,1.700000,0.036000,23.000000,108.250000,0.991753,3.090000,0.410000,9.500000,3.000000
50%,6.800000,0.260000,0.310000,5.200000,0.043000,34.000000,134.000000,0.993800,3.180000,0.470000,10.400000,4.000000
75%,7.300000,0.320000,0.390000,10.100000,0.050000,46.000000,168.000000,0.996200,3.280000,0.550000,11.400000,4.000000
max,11.800000,1.100000,1.000000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.050000,7.000000

Nie widać aby pojawiły się jakieś nierealne dane, które znacznie się różnią lub braki danych, więc można stwierdzić że pod tym względem dane są odpowiednio przygotowane.

In [10]:
white_wines[white_wines.duplicated(keep=False)]

,Fixed acidity,Volatile acidity,Citric acid,Residual sugar,Chlorides,Free sulfur dioxide,Total sulfur dioxide,Density,pH,Sulphates,Alcohol,Quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,4
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,4
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,4
3,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,4
5,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,4
...,...,...,...,...,...,...,...,...,...,...,...,...
3883,6.4,0.23,0.35,10.3,0.042,54.0,140.0,0.99670,3.23,0.47,9.2,3
3899,7.0,0.36,0.35,2.5,0.048,67.0,161.0,0.99146,3.05,0.56,11.1,4
3900,7.0,0.36,0.35,2.5,0.048,67.0,161.0,0.99146,3.05,0.56,11.1,4
3904,7.1,0.23,0.39,13.7,0.058,26.0,172.0,0.99755,2.90,0.46,9.0,4
3905,7.1,0.23,0.39,13.7,0.058,26.0,172.0,0.99755,2.90,0.46,9.0,4

Widać że duplikaty pojawiają się w zbiorze, więc najrozsądniej będzie je usunąć.

In [11]:
white_wines.drop_duplicates(inplace=True)

In [12]:
white_wines

,Fixed acidity,Volatile acidity,Citric acid,Residual sugar,Chlorides,Free sulfur dioxide,Total sulfur dioxide,Density,pH,Sulphates,Alcohol,Quality
0,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,4
1,6.3,0.300,0.34,1.60,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,4
2,8.1,0.280,0.40,6.90,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,4
4,6.2,0.320,0.16,7.00,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,4
7,8.1,0.220,0.43,1.50,0.044,28.0,129.0,0.99380,3.22,0.45,11.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...
3929,4.9,0.235,0.27,11.75,0.030,34.0,118.0,0.99540,3.07,0.50,9.4,4
3930,6.2,0.210,0.29,1.60,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,4
3931,6.6,0.320,0.36,8.00,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,3
3932,6.5,0.240,0.19,1.20,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,4
3933,5.5,0.290,0.30,1.10,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,5